### ISSUE TITLE
希望增加钢琴的声音

### ISSUE THREAD

**Issue by jerry011235** [yingDev/Tickeys#1]
这个软件太好玩了！
希望按不同的键，能发出不同的钢琴声音，参考[开源软件freepiano][1]。
另外希望windows版本，运行后右下角任务栏有一个通知图标，有“设置”，“退出”和“关于”，可以呼出设置面板（就不用qaz123了），里面有“随开机启动”。

  [1]: http://freepiano.tiwb.com/cn/

**Comment by yingDev** [comment]
我添加试试～
想象是美好的，现实可能很骨感，因为差异稍大的声音，都很容易分散注意力，那样就和软件的目标背道而驰了。

**Comment by luohuaDev** [comment]
有意思的应用。赞个。
设置页面的字体很是模糊。我用的是RMBP2015 OSX10.10.2。
