### ISSUE TITLE
在iTerm2.app下打字无声音...

### ISSUE THREAD

**Issue by jzk** [yingDev/Tickeys#11]
好奇怪，其他地方都有声音，好欢乐，到终端下面就没有了。但是Terminal.app是有声音的

[iTerm2](http://iterm2.com)

**Comment by yingDev** [comment]
我一直用iTerm2... 但是并没有发现这种现象。
目前为止，我所知道的没有声音的情况，只有在密码框，而这种情况是符合预期的。

也许你可以试试从终端 `sudo /Applications/Tickeys.app/Contents/MacOS/Tickeys`  看会是啥现象。。。

**Comment by jzk** [comment]
sudo /Applications/Tickeys.app/Contents/MacOS/Tickeys
request_accessiblility
loading audio:/Applications/Tickeys.app/Contents/MacOS/../Resources/data/bubble/1.wav
loading audio:/Applications/Tickeys.app/Contents/MacOS/../Resources/data/bubble/2.wav
loading audio:/Applications/Tickeys.app/Contents/MacOS/../Resources/data/bubble/3.wav
loading audio:/Applications/Tickeys.app/Contents/MacOS/../Resources/data/bubble/4.wav
loading audio:/Applications/Tickeys.app/Contents/MacOS/../Resources/data/bubble/5.wav
loading audio:/Applications/Tickeys.app/Contents/MacOS/../Resources/data/bubble/6.wav
loading audio:/Applications/Tickeys.app/Contents/MacOS/../Resources/data/bubble/7.wav
loading audio:/Applications/Tickeys.app/Contents/MacOS/../Resources/data/bubble/8.wav
loading audio:/Applications/Tickeys.app/Contents/MacOS/../Resources/data/bubble/enter.wav
Response: {"Version":"0.4.1","WhatsNew":"修正因在10.11下编译导致10.10中无法运行的问题"}
ver=0.4.1
userNotificationCenterDidDeliverNotification
Settings!
SettingsDelegate::new::REGISTER_APPDELEGATE
loadValues
makeKeyAndOrderFront:
Quit
SettingsDelegate::windowWillClose
IT LOADED YAY%

**Comment by jzk** [comment]
经过你提醒，我的iTerm里面有个Secure Keyboard Entry的钩钩之前打着。。 去掉就好了
<img width="262" alt="screen shot 2015-10-16 at 11 55 15 pm" src="https://cloud.githubusercontent.com/assets/48630/10546577/5ea9e0b4-7461-11e5-9c44-b85666c205dc.png">
