### ISSUE TITLE
Ubuntu14.04下无法隐藏

### ISSUE THREAD

**Issue by buqing2009** [yingDev/Tickeys#20]
首先先对作者的贡献表示敬意，要多多向您学习 @yingDev 
本人在Mac下使用过此软件感觉非常不错，然后在ubuntu下也试了下，发现另一个bug，无法隐藏希望 @yingDev 能尽快修复谢谢，再次表示敬意！

**Comment by yingDev** [comment]
![Linux版](https://github.com/BillBillBillBill/Tickeys-linux) 由 @BillBillBillBill 同学实现.

**Comment by BillBillBillBill** [comment]
@buqing2009 你好，请安装xdotool: sudo apt-get install xdotool

**Comment by buqing2009** [comment]
@BillBillBillBill 可以了非常感谢！
