### ISSUE TITLE
Bug(打字机/机械键盘)

### ISSUE THREAD

**Issue by acethical** [yingDev/Tickeys#4]
Bug描述: 版本1.0.1，问题为使用打字机/机械键盘音效，使用一段时间就会停止发音。从软件界面点退出，再进入，仍然不会发音，只有冒泡和剑气会有声音。
出现此问题后，需从任务管理器强制结束进程再进入，才会恢复正常

**Comment by yingDev** [comment]
这个问题是win版的, 这个repo是mac版的.
出现问题后, 无法使用qaz123吗?

**Comment by acethical** [comment]
Win版，出现问题后，qaz123仍在运行，可打开设置菜单，但无声音。必须在任务管理器里退出再进，才能再次有效
