### ISSUE TITLE
关于1.0.0版本无法获得mac辅助功能授权的bug

### ISSUE THREAD

**Issue by pearamily** [yingDev/Tickeys#49]
安装好之后，会有到mac 系统隐私》辅助功能 授权tickeys 的复选框 ，点击时候，tickeys 无法显示完成
关闭tickeys之后，重新打开重复上面的操作，发现 辅助功能的授权被被重新置灰了

**Comment by AlanNgaiJX** [comment]
同样问题 从0.5版本直接安装1.0版本 ， 打开app Tickeys需要使用辅助功能 ，此时我的功能列表中已勾选了tickeys，完成按钮始终为灰

**Comment by tcqiuyu** [comment]
同样的问题

**Comment by yingDev** [comment]
重启系统应该就可以了

**Comment by pearamily** [comment]
官网有说 需要重启系统，然后好使了。
reboot the system then it works.

**Comment by rootsongjc** [comment]
- tickeys 版本：1.0.0
- macOS 版本：10.15.6 Catalina

重启系统后，发现确实是好了，但是我的 Mac 上并没有在系统状态栏中显示 TK 的 icon，而且打开 tickeys 应用虽然打字后有气泡声了，但是没有弹出配置窗口。

**Comment by qiuyimo** [comment]
重启以后还是不行.

**Comment by rootsongjc** [comment]
重启后也没办法设置，我现在已经放弃 1.0.0 的 tickeys 了，等新版本吧。

**Comment by July-L** [comment]
同样的问题，过来看看有啥解决办法不。。。

**Comment by xiahCheung** [comment]
> 重启后也没办法设置，我现在已经放弃 1.0.0 的 tickeys 了，等新版本吧。

新版本发大概什么是时候出呢

**Comment by sqzhang-jeremy** [comment]
> 重启后也没办法设置，我现在已经放弃 1.0.0 的 tickeys 了，等新版本吧。

Have u tried the new release version 1.1.0? It still does't work for me....
